use filesystem;

insert into series
	(series_name)
values
	('Castle'),
	('Fringe'),
	('Mac Gyver'),
	('The Big Bang Theory')
;

set @castle_id = ( select series_id from series where series_name = 'Castle' );
set @fringe_id = ( select series_id from series where series_name = 'Fringe' );
set @macgyver_id = ( select series_id from series where series_name = 'Mac Gyver' );
set @thebigbangtheory_id = ( select series_id from series where series_name = 'The Big Bang Theory' );

insert into season
	(season_name, season_series_id)
values
	('Season 01', @castle_id),
	('Season 02', @castle_id),
	('Season 01', @fringe_id),
	('Season 01', @macgyver_id),
	('Season 02', @macgyver_id),
	('Season 03', @macgyver_id),
	('Season 04', @macgyver_id),
	('Season 01', @thebigbangtheory_id),
	('Season 02', @thebigbangtheory_id),
	('Season 03', @thebigbangtheory_id)
;

insert into episode
	(episode_name, episode_season_id)
values
	('Flowers for Your Grave', 1),
	('Nanny McDead', 1),
	('Hedge Fund Homeboys', 1),
	('Hell Hath No Fury', 1),
	('A Chill Goes Through Her Veins', 1),
	('Always Buy Retail', 1),
	('Home Is Where The Heart Stops', 1),
	('Ghosts', 1),
	('Little Girl Lost', 1),
	('A Death in the Family', 1),
	('Deep in Death', 2),
	('The Double Down', 2),
	('Inventing the Girl', 2),
	('Fool Me Once...', 2),
	('When the Bough Breaks', 2),
	('Vampire Weekend', 2),
	('Famous Last Words', 2),
	('Kill the Messenger', 2),
	('Love Me Dead', 2),
	('One Man\'s Treasure', 2),
	('The Fifth Bullet', 2),
	('A Rose for Everafter', 2),
	('Sucker Punch', 2),
	('The Third Man', 2),
	('Suicide Squeeze', 2),
	('The Mistress Always Spanks Twice', 2),
	('Tick Tick Tick', 2),
	('Boom!', 2),
	('Wrapped Up in Death', 2),
	('The Late Shaft', 2),
	('Den of Thieves', 2),
	('Food to Die For', 2),
	('Overkill', 2),
	('A Deadly Game', 2),
	('Pilot', 3),
	('The Same Old Story', 3),
	('The Ghost Network', 3),
	('The Arrival', 3),
	('Power Hungry', 3),
	('The Cure', 3),
	('In Which We Meet Mr. Jones', 3),
	('The Equation', 3),
	('The Dreamscape', 3),
	('Safe', 3),
	('Bound', 3),
	('The No-Brainer', 3),
	('The Transformation', 3),
	('Ability', 3),
	('Inner Child', 3),
	('Unleashed', 3),
	('Bad Dreams', 3),
	('Midnight', 3),
	('The Road Not Taken', 3),
	('There\'s More Than One of Everything', 3),
	('Pilot', 4),
	('The Golden Triangle', 4),
	('Thief of Budapest', 4),
	('The Gauntlet', 4),
	('The Heist', 4),
	('Trumbos World', 4),
	('Last Stand', 4),
	('Hellfire', 4),
	('The Prodigal', 4),
	('Target MacGyver', 4),
	('Nightmares', 4),
	('Deathlock', 4),
	('Flames End', 4),
	('Countdown', 4),
	('The Enemy Within', 4),
	('Everytime She Smiles', 4),
	('To Be a Man', 4),
	('Ugly Duckling', 4),
	('Slow Death', 4),
	('The Escape', 4),
	('A Prisoner of Conscience', 4),
	('The Assassin', 5),
	('The Human Factor', 5),
	('The Eraser', 5),
	('Twice Stung', 5),
	('The Wish Child', 5),
	('Final Approach', 5),
	('Jack of Lies', 5),
	('The Road Not Taken', 5),
	('Eagles', 5),
	('Silent World', 5),
	('Three for the Road', 5),
	('Phoenix Under Siege', 5),
	('Family Matter', 5),
	('Soft Touch', 5),
	('Birth Day', 5),
	('Pirates', 5),
	('Out in the Cold', 5),
	('Dalton Jack of Spies', 5),
	('Partners', 5),
	('Bushmaster', 5),
	('Friends', 5),
	('D. O. A. MacGyver', 5),
	('For Love or Money', 5),
	('Lost Love Part 1', 6),
	('Lost Love Part 2', 6),
	('Back From the Dead', 6),
	('Ghost Ship', 6),
	('Fire and Ice', 6),
	('GX-1', 6),
	('Jack in the Box', 6),
	('The Widowmaker', 6),
	('Hell Week', 6),
	('Blow Out', 6),
	('Kill Zone', 6),
	('Early Retirement', 6),
	('Thin Ice', 6),
	('The Odd Triple', 6),
	('The Negotiator', 6),
	('The Spoilers', 6),
	('Mask of the Wolf', 6),
	('Rock the Cradle', 6),
	('The Endangered', 6),
	('Murderers Sky', 6),
	('The Secret of Parker House', 7),
	('Blood Brothers', 7),
	('The Outsiders', 7),
	('On a Wing and a Prayer', 7),
	('Collision Course', 7),
	('The Survivors', 7),
	('Deadly Dreams', 7),
	('Ma Dalton', 7),
	('Cleo Rocks', 7),
	('Fraternity of Thieves', 7),
	('The Battle of Tommy Giordano', 7),
	('The Challenge', 7),
	('Runners', 7),
	('Gold Rush', 7),
	('The Invisible Killer', 7),
	('Brainwashed', 7),
	('Easy Target', 7),
	('Renegade', 7),
	('Unfinished Business', 7),
	('Pilot', 8),
	('The Big Bran Hypothesis', 8),
	('The Fuzzy Boots Corollary', 8),
	('The Luminous Fish Effect', 8),
	('The Hamburger Postulate', 8),
	('The Middle Earth Paradigm', 8),
	('The Dumpling Paradox', 8),
	('The Grasshopper Experiment', 8),
	('The Cooper-Hofstadter Polarization', 8),
	('The Loobenfeld Decay', 8),
	('The Pancake Batter Anomaly', 8),
	('The Jerusalem Duality', 8),
	('The Bat Jar Conjecture', 8),
	('The Nerdvana Annihilation', 8),
	('The Porkchop Indeterminacy', 8),
	('The Peanut Reaction', 8),
	('The Tangerine Factor', 8),
	('The Bad Fish Paradigm', 9),
	('The Codpiece Topology', 9),
	('The Barbarian Sublimation', 9),
	('The Griffin Equivalency', 9),
	('The Euclid Alternative', 9),
	('The Cooper-Nowitzki Theorem', 9),
	('The Panty Pinata Polarization', 9),
	('The Lizard-Spock Expansion', 9),
	('The White Asparagus Triangulation', 9),
	('The Vartabedian Conundrum', 9),
	('The Bath Item Gift Hypothesis', 9),
	('The Killer Robot Instability', 9),
	('The Friendship Algorithm', 9),
	('The Financial Permeability', 9),
	('The Maternal Capacitance', 9),
	('The Cushion Saturation', 9),
	('The Terminator Decoupling', 9),
	('The Work Song Nanocluster', 9),
	('The Dead Hooker Juxtaposition', 9),
	('The Hofstadter Isotope', 9),
	('The Vegas Renormalization', 9),
	('The Classified Materials Turbulence', 9),
	('The Monopolar Expedition', 9),
	('The Electric Can Opener Fluctuation', 10),
	('The Jiminy Conjecture', 10),
	('The Gothowitz Deviation', 10),
	('The Pirate Solution', 10),
	('The Creepy Candy Coating Corollary', 10),
	('The Cornhusker Vortex', 10),
	('The Guitarist Amplification', 10),
	('The Adhesive Duck Deficiency', 10),
	('The Vengeance Formulation', 10),
	('The Gorilla Experiment', 10),
	('The Maternal Congruence', 10),
	('The Psychic Vortex', 10),
	('The Bozeman Reaction', 10),
	('The Einstein Approximation', 10),
	('The Large Hadron Collision', 10),
	('The Excelsior Acquisition', 10),
	('The Precious Fragmentation', 10),
	('The Pants Alternative', 10),
	('The Wheaton Recurrence', 10),
	('The Spaghetti Catalyst', 10),
	('The Plimpton Stimulation', 10),
	('The Staircase Implementation', 10),
	('The Lunar Excitation', 10)
;